language: node_js
sudo: false
node_js:
  - "9.4.0"
install:
  - npm install
before_script:
  #- sed 's/AUTH0_DOMAIN={DOMAIN}/AUTH0_DOMAIN=$domain/' .env.example > .env
  - cp .env.example .env
  - sed 's/AUTH0_DOMAIN={DOMAIN}/AUTH0_DOMAIN=$domain/' . env
  - sed 's/AUTH0_AUDIENCE={AUDIENCE}/AUTH0_AUDIENCE=$audience/' . env

  - npm start & sleep 7
script:
  - cd test
  - ls
  # npm install && npm install asyncawait
  # - npm test
