language: node_js
sudo: false
node_js:
  - "9.4.0"
install:
  - npm install
before_script:
  - echo "AUTH0_DOMAIN=$domain" >> .env
  - echo "AUTH0_AUDIENCE=$audience" >> .env 
  - npm start & sleep 7
script:
  - cd test && npm install
  - npm test
