language: node_js
sudo: false
node_js:
  - "9.4.0"
install:
  - npm install
before_script:
  - cp .env.example .env
  - sed "/AUTH0_DOMAIN={DOMAIN}/AUTH0_DOMAIN=$domain/" .env
  - sed "/AUTH0_AUDIENCE={API_AUDIENCE}/AUTH0_AUDIENCE=$audience/" .env
  - npm start & sleep 7
script:
  - cd test
  - cp .env.example .env
  #- sed 's/AUTH0_DOMAIN={DOMAIN}/AUTH0_DOMAIN=$domain/' .env
  #- sed 's/AUTH0_AUDIENCE={API_ID}/AUTH0_AUDIENCE=$audience/' .env
  #- sed 's/AUTH0_CLIENT_ID_1={CLIENT_ID_1}/AUTH0_CLIENT_ID_1=$id1' .env
  #- sed 's/AUTH0_CLIENT_SECRET_1={CLIENT_SECRET_1}/AUTH0_CLIENT_SECRET_1=$secret1' .env
  #- sed 's/AUTH0_CLIENT_ID_2={CLIENT_ID_2}/AUTH0_CLIENT_ID_2=$id2' .env
  #- sed 's/AUTH0_CLIENT_SECRET_2={CLIENT_SECRET_2}/AUTH0_CLIENT_SECRET_2=$secret2' .env
  #- sed 's/AUTH0_CLIENT_ID_3={CLIENT_ID_3}/AUTH0_CLIENT_ID_3=$id3' .env
  #- sed 's/AUTH0_CLIENT_SECRET_3={CLIENT_SECRET_3}/AUTH0_CLIENT_SECRET_3=$secret3' .env
  #- sed 's/AUTH0_CLIENT_ID_4={CLIENT_ID_4}/AUTH0_CLIENT_ID_4=$id4' .env
  #- sed 's/AUTH0_CLIENT_SECRET_4={CLIENT_SECRET_4}/AUTH0_CLIENT_SECRET_4=$secret4' .env
  #- npm install && npm test
