version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.4
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
          
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: 
          name: npm install
          command: npm install
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: 
          name: test
          command: npm test
 deployment:
  staging:
    branch: master
    heroku:
      appname: foo-bar-123   
