version: 2
jobs:
  build:
    docker:
      image: circleci/node:9.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            docker build --rm=false -t auth0-express-api-rs256
      - run:
          name: Execute server on background for tests
          command: | 
            docker run --env-file .env -p 3010:3010 -it auth0-express-api-rs256 npm start
          background: true
      - run: 
          name: Test
          command: npm test
