version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      
      - run: 
          name: Prepare .env variables for server
          command: |
            echo "AUTH0_DOMAIN=$domain" >> .env
            echo "AUTH0_AUDIENCE=$audience" >> .env
         
      - run:
          name: Execute dockerized version
          command: sh exec.sh
          #background: true
      
