version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build image
          working_directory: ~/app/server
          command: |
            set -x
            docker-compose -f docker-compose-test.yml build
      - run:
          name: Run tests
          working_directory: ~/app/server
          command: |
            set -x
            docker-compose -f docker-compose-test.yml run test yarn run test
