version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/node: 9.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t auth0-express-api-rs256 .
          
      - run:
          name: Run image
          command: docker run --env-file .env -p 3010:3010 -it auth0-express-api-rs256
      
