
version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
           
    steps:
      - checkout
      - run: 
          name: Set .env file
          command: |
              echo "AUTH0_DOMAIN=$domain" >> .env
              echo "AUTH0_AUDIENCE=$audience" >> .env
          
      - run: docker build -t auth0-express-api-rs256 .
      - run: 
           name: background server
           command: docker run --name rafa-test --env-file .env -p 3010:3010 -it auth0-express-api-rs256 
           background: true
      
      - run: sleep 10
           
      - run: docker inspect --format '{{ .NetworkSettings.IPAddress }}' rafa-test
      - run: netstat -ano            
      - run: curl --verbose http://localhost:3010/api/public
