
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.4.0
      #- image: docker:17.05.0-ce-git
      
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Set .env file
          command: |
              echo "AUTH0_DOMAIN=$domain" >> .env
              echo "AUTH0_AUDIENCE=$audience" >> .env
          
      - run: docker build -t auth0-express-api-rs256 .
      - run: 
           name: background server
           command: |
              docker run --name rafa-test --env-file .env -p 3010:3010 -it auth0-express-api-rs256 
           background: true
      
      - run: sleep 10
      
      - run: docker exec rafa-test curl http://localhost:3010/api/public
           
      #- run: docker ps
      #- run: 
      #    name: inspections
      #    command: docker inspect --format '{{ .NetworkSettings.IPAddress }}' rafa-test
              

      #- run: curl -i http://172.17.0.2:3010/api/public
