version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node: 9.4.0
    steps:
      - checkout
      - setup_remote_docker
      
      - run: 
          name: Prepare .env variables for server
          command: |
            echo "AUTH0_DOMAIN=$domain" >> .env
            echo "AUTH_AUDIENCE=$audience" >> .env
         
      - run:
          name: Execute dockerized version
          command: sh exec.sh
          background
      
