version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
      #- image: circleci/node:9.4.0
      
    steps:
      - checkout
      - setup_remote_docker
      
      - run: docker-machine ip
